name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]

    defaults:
      run:
        # this is needed, because otherwise conda env is not available
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get -y --no-install-recommends install -y ghostscript

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          cache-environment: false
          cache-downloads: true

      - name: Set directory names
        run: |
          echo "MODELDIR=$HOME/Downloads/models" >> $GITHUB_ENV
          echo "MYCACHE=$HOME/Downloads/xspec" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/.local/bin/" >> $GITHUB_ENV

      - name: Cache models
        uses: pat-s/always-upload-cache@v3.0.11
        id: cache-downloads
        with:
          path: ${{ env.MODELDIR }}
          key: cache-downloads

      - name: Download models (if necessary)
        run: |
             mkdir -p $MODELDIR
             pushd $MODELDIR
             wget -q -nc https://zenodo.org/record/1169181/files/uxclumpy-cutoff.fits https://zenodo.org/records/2224651/files/wedge.fits https://zenodo.org/records/2224472/files/diskreflect.fits
             popd

      - name: Install python dependencies
        run: |
          micromamba install --override-channels -c https://cxc.cfa.harvard.edu/conda/ciao -c conda-forge xspec-modelsonly "matplotlib>=3.5" ultranest "coverage<7.0.0" coveralls==3.3.1 scipy jax h5py astropy requests cython tqdm coverage toml flake8 pycodestyle pydocstyle pytest pytest-html pytest-xdist h5py joblib &&
          echo "--- Environment dump start ---" &&
          env &&
          echo "--- Environment dump end ---" &&
          pip install git+https://github.com/JohannesBuchner/coverage-lcov &&
          sudo sed -i '/PDF/s/none/read|write/' /etc/ImageMagick-6/policy.xml &&
          pip uninstall -y h5py &&
          pip install --no-cache-dir -r pip-requirements.txt git+https://github.com/cxcsds/xspec-models-cxc

      - name: Conda info
        run: micromamba info
      - name: Conda list
        run: micromamba list
      - name: Conda paths
        run: |
          pwd
          echo $PATH
          ls $CONDA/bin/
          which coverage

      - name: Lint with flake8
        run: flake8 tinyxsf

      - name: Check code style
        run: pycodestyle tinyxsf

      - name: Check doc style
        run: pydocstyle tinyxsf

      - name: Check install
        run: |
          python -c "import numpy";
          python -c "import xspec_models_cxc"

      - name: Prepare testing
        run: |
          echo "backend: Agg" > matplotlibrc

      - name: Test with pytest
        run: PYTHONPATH=. coverage run -p -m pytest

      - name: Run simple example
        run: PYTHONPATH=. coverage run -p simple.py

      - name: Run vectorized example
        run: PYTHONPATH=. coverage run -p simplev.py

      #- name: Run optimized nested sampling example
      #  run: PYTHONPATH=. coverage run -p optsimple.py

      - name: Install package
        run: pip install .

      - name: Coverage report
        run: |
          coverage combine
          coverage report
          coverage-lcov
          # make paths relative
          sed -i s,$PWD/,,g lcov.info

      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.github_token }}
